language: node_js
node_js:
  - stable

before_install:
  - cd reference-implementation
script:
  - npm run lint
  - npm test
  - cd .. && bash ./deploy.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - ENCRYPTION_LABEL: "b39b94f92b55"
    - COMMIT_AUTHOR_EMAIL: "guybedford@gmail.com"
